// USER_TABLE 생성
CREATE TABLE USER_TABLE (
    USER_ID VARCHAR2(100 BYTE) NOT NULL,
    USER_PWD VARCHAR2(100 BYTE) NOT NULL,
    USER_NAME VARCHAR2(100 BYTE) NOT NULL,
    STATUS VARCHAR2(50 BYTE) DEFAULT 'N',
    CREATED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    UPDATED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USER_TABLE PRIMARY KEY (USER_ID)
);

SELECT * FROM user_table;

// WIN_COUNT 추가
ALTER TABLE USER_TABLE
ADD WIN_COUNT NUMBER DEFAULT 0;

SELECT * FROM user_table;

// USER_TABLE 더미 데이터 추가
INSERT INTO USER_TABLE (USER_ID, USER_PWD, USER_NAME, STATUS, WIN_COUNT) 
VALUES ('user1@naver.com', 'password1', '포챠코', 'A', 20);

INSERT INTO USER_TABLE (USER_ID, USER_PWD, USER_NAME, STATUS, WIN_COUNT) 
VALUES ('user4@naver.com', 'password4', '이디현', 'A', 8);

INSERT INTO USER_TABLE (USER_ID, USER_PWD, USER_NAME, STATUS, WIN_COUNT) 
VALUES ('user5@naver.com', 'password5', '상요이', 'A', 5);

INSERT INTO USER_TABLE (USER_ID, USER_PWD, USER_NAME, STATUS, WIN_COUNT) 
VALUES ('user2@naver.com', 'password2', '춘시기', 'A', 15);

INSERT INTO USER_TABLE (USER_ID, USER_PWD, USER_NAME, STATUS, WIN_COUNT) 
VALUES ('user3@naver.com', 'password3', '오목신', 'A', 10);

// 랭킹 3위까지
SELECT USER_NAME, WIN_COUNT
FROM (
    SELECT USER_NAME, WIN_COUNT
    FROM USER_TABLE
    ORDER BY WIN_COUNT DESC
)
WHERE ROWNUM <= 3;

// PARTNER 생성
CREATE TABLE PARTNER
(
    IDX           INT             NOT NULL, 
    USER_ID       VARCHAR(100)    NOT NULL, 
    PARTNER_ID    VARCHAR(100)    NULL, 
    STATUS        VARCHAR(1)      NULL, 
    CREATED       DATE            NULL, 
     PRIMARY KEY (IDX)
);

-- Auto Increment를 위한 Sequence 추가 SQL - PARTNER.IDX
CREATE SEQUENCE PARTNER_SEQ
START WITH 1
INCREMENT BY 1;


-- DROP TRIGGER PARTNER_AI_TRG; 

 DROP SEQUENCE PARTNER_SEQ; 

-- 컬럼 Comment 설정 SQL - PARTNER.IDX
COMMENT ON COLUMN PARTNER.IDX IS 'IDX';

-- 컬럼 Comment 설정 SQL - PARTNER.USER_ID
COMMENT ON COLUMN PARTNER.USER_ID IS 'USER_ID';

-- 컬럼 Comment 설정 SQL - PARTNER.PARTNER_ID
COMMENT ON COLUMN PARTNER.PARTNER_ID IS 'PARTNER_ID';

-- 컬럼 Comment 설정 SQL - PARTNER.STATUS
COMMENT ON COLUMN PARTNER.STATUS IS 'STATUS';

-- 컬럼 Comment 설정 SQL - PARTNER.CREATED
COMMENT ON COLUMN PARTNER.CREATED IS 'CREATED';

// PARTNER 더미 데이터 추가
INSERT INTO PARTNER VALUES(1,'PARTNER1','PARTNER2', 'W', SYSDATE);
INSERT INTO PARTNER VALUES(2,'PARTNER1','PARTNER2', 'W', SYSDATE);
INSERT INTO PARTNER VALUES(3,'PARTNER1','PARTNER2', 'W', SYSDATE);
INSERT INTO PARTNER VALUES(4,'PARTNER1','PARTNER2', 'W', SYSDATE);
INSERT INTO PARTNER VALUES(5,'PARTNER1','PARTNER2', 'W', SYSDATE);
INSERT INTO PARTNER VALUES(6,'PARTNER1','PARTNER2', 'L', SYSDATE);
INSERT INTO PARTNER VALUES(7,'PARTNER1','PARTNER1', 'L', SYSDATE);
INSERT INTO PARTNER VALUES(8,'PARTNER2','PARTNER1', 'W', SYSDATE);
INSERT INTO PARTNER VALUES(9,'PARTNER2','PARTNER1', 'W', SYSDATE);
INSERT INTO PARTNER VALUES(10,'PARTNER2','PARTNER1','L', SYSDATE); 
INSERT INTO PARTNER VALUES(11,'PARTNER2','PARTNER1','L', SYSDATE); 
INSERT INTO PARTNER VALUES(12,'PARTNER2','PARTNER1','L', SYSDATE); 
INSERT INTO PARTNER VALUES(13,'PARTNER2','PARTNER1','L', SYSDATE); 
INSERT INTO PARTNER VALUES(14,'PARTNER3','PARTNER4','W', SYSDATE); 
INSERT INTO PARTNER VALUES(15,'PARTNER3','PARTNER4','W', SYSDATE); 
INSERT INTO PARTNER VALUES(16,'PARTNER3','PARTNER4','L', SYSDATE); 
INSERT INTO PARTNER VALUES(17,'PARTNER3','PARTNER4','L', SYSDATE); 
INSERT INTO PARTNER VALUES(18,'PARTNER3','PARTNER4','L', SYSDATE); 
INSERT INTO PARTNER VALUES(19,'PARTNER3','PARTNER4','L', SYSDATE); 
INSERT INTO PARTNER VALUES(20,'PARTNER3','PARTNER4','L', SYSDATE); 
INSERT INTO PARTNER VALUES(21,'PARTNER3','PARTNER4','L', SYSDATE); 
INSERT INTO PARTNER VALUES(23,'PARTNER4','PARTNER3','L', SYSDATE); 
INSERT INTO PARTNER VALUES(24,'PARTNER4','PARTNER3','L', SYSDATE); 
INSERT INTO PARTNER VALUES(25,'PARTNER4','PARTNER3','W', SYSDATE); 
INSERT INTO PARTNER VALUES(26,'PARTNER4','PARTNER3','W', SYSDATE); 
INSERT INTO PARTNER VALUES(27,'PARTNER4','PARTNER3','W', SYSDATE); 
INSERT INTO PARTNER VALUES(28,'PARTNER4','PARTNER3','W', SYSDATE); 
INSERT INTO PARTNER VALUES(29,'PARTNER4','PARTNER3','W', SYSDATE); 
INSERT INTO PARTNER VALUES(30,'PARTNER4','PARTNER3','W', SYSDATE); 

// 더미 데이터 수정
-- PARTNER1 -> user1@naver.com
UPDATE PARTNER
   SET USER_ID = 'user1@naver.com'
 WHERE USER_ID = 'PARTNER1';

-- PARTNER2 -> user2@naver.com
UPDATE PARTNER
   SET USER_ID = 'user2@naver.com'
 WHERE USER_ID = 'PARTNER2';

-- PARTNER3 -> user3@naver.com
UPDATE PARTNER
   SET USER_ID = 'user3@naver.com'
 WHERE USER_ID = 'PARTNER3';

-- PARTNER4 -> user4@naver.com
UPDATE PARTNER
   SET USER_ID = 'user4@naver.com'
 WHERE USER_ID = 'PARTNER4';

SELECT * FROM PARTNER
ORDER BY user_ID;

// 누락 추가
INSERT INTO PARTNER VALUES(22, 'PARTNER4', 'PARTNER3', 'L', SYSDATE);

UPDATE PARTNER
   SET USER_ID = 'user4@naver.com'
 WHERE USER_ID = 'PARTNER4' AND idx = 22;

SELECT DISTINCT USER_ID FROM PARTNER;

// PARTNER와 USER_TABLE JOIN 후 랭킹 실행 > USER_NAME 때문에
SELECT *
FROM (
      SELECT ROUND((A.WIN_COUNT / (A.WIN_COUNT + A.LOSE_COUNT)) * 100, 1) AS RANK,
             A.USER_ID,
             U.USER_NAME,
             A.WIN_COUNT,
             A.LOSE_COUNT,
             (A.WIN_COUNT + A.LOSE_COUNT) AS TOTAL_COUNT
        FROM (
              SELECT COUNT(DECODE(STATUS, 'W', 1)) AS WIN_COUNT,
                     COUNT(DECODE(STATUS, 'L', 1)) AS LOSE_COUNT,
                     USER_ID
                FROM PARTNER
               GROUP BY USER_ID
             ) A
        JOIN USER_TABLE U
          ON A.USER_ID = U.USER_ID
       ORDER BY RANK DESC
     )
WHERE ROWNUM <= 3;

commit;